### ISSUE TITLE
Missing symbol in firefox

### ISSUE THREAD

**Issue by Sinled** [dandln/Foundry-VTT-Prettier-Login-Screen#13]
Hi, 
i am using v10.291 and latest version of package and there are broken icon in firefox for `join game session` button

And in chrome there are no icon at all.

<img width="422" alt="Screenshot 2023-03-30 at 10 12 09" src="https://user-images.githubusercontent.com/1402135/228757739-c8b19363-fb2f-455c-a3d4-2305f07baeff.png">

it seems `content: "\1F846";` symbol is missing from Signika font

I think i can fix it in styles manually, but these changes will be lost with package update?

**Comment by dandln** [comment]
Hey @Sinled, apologies for the late response and thanks so much for flagging this! Really weird, looks like current browsers stopped rendering the `heavy arrow` unicode characters altogether. I've replaced it with a standard arrow now, and updated the module to version 10.2 which has the fix in it. You'll need to uninstall the module and re-install it through the manifest URL as unfortunately the old version has a broken URL in it. Hope this helps!
